#!/bin/sh -e

test -e /akkada/bin/akkada.pl || exit 0
test -e /akkada/etc/akkada.shell || exit 0

. /akkada/etc/akkada.shell

. /lib/lsb/init-functions

RUNASUSER=$OSLogin
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true

if [ -z "$UGID" ]; then
  echo "User $RUNASUSER does not exist" >&2
  exit 1
fi

RETVAL=0

case "$1" in
	start)
                if [ -f "$PIDFILE" ] && ps `cat $PIDFILE` >/dev/null 2>&1; then 
                        echo "akk@da is already running. exiting.";
                        exit 1;
                fi

                $CFGCHECK
                RETVAL=$?
                [ $RETVAL -ne 0 ] && exit $RETVAL

                if [ -x $EXECPRE ]; then
                        log_begin_msg "Starting akk@da NMS system preload script"
                        $EXECPRE
                        RETVAL=$?
                        if [ $RETVAL -ne 0 ]; then
                                echo "   error; check preload script $EXECPRE"
                                log_end_msg $RETVAL
                        fi
                        log_end_msg $RETVAL;
                fi


		log_begin_msg "Starting akk@da NMS system..."
  		start-stop-daemon --start --quiet --chuid $OSLogin --pidfile $PIDFILE --exec $EXEC
                ps -ef | grep akkada.pl | grep -E "^akkada" | awk '{print $2}' > $PIDFILE
		log_end_msg $?
  		;;
	stop)
		log_begin_msg "Stopping akk@da NMS system..."
                if [ ! -e "$PIDFILE" ]; then 
                        echo "   akk@da is already stopped."
		        log_end_msg 1
                fi
  		start-stop-daemon --stop --pidfile $PIDFILE
                sleep 5
                if [ -f "$PIDFILE" ] && ps `cat $PIDFILE` >/dev/null 2>&1; then 
		        log_end_msg 1
                        exit 1;
                fi
		rm -f $PIDFILE
		log_end_msg $?
  		;;
	*)
  		log_success_msg "Usage: /akkada/etc/init.d/akkada_ubuntu {start|stop}"
  		exit 1
		;;
esac

exit 0
