#!/bin/bash

export AKKADA=/akkada

. $AKKADA/etc/akkada.shell

. /etc/init.d/functions

CDIR=`pwd`

PIDFILE=$AKKADA/var/akkada.pid

cd $AKKADA

EXEC=$AKKADA/bin/akkada.pl
CFGCHECK=$AKKADA/bin/cfgcheck.pl
EXECPRE=$AKKADA/bin/akkada_pre

RETVAL=0

start() {
	$CFGCHECK
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit $RETVAL
        status $EXEC > /dev/null
	RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "akk@da is already running. exiting.";
            exit 1;
        fi
	if [ -e $EXECPRE ]; then
 	    echo "Starting akk@da NMS system preload script"
            $EXECPRE
	    RETVAL=$?
	    if [ $RETVAL -ne 0 ]; then
                echo "error; check preload script $EXECPRE"
                exit 1
            fi
        fi

        rm -f $AKKADA/var/control/*

 	echo -n $"Starting akk@da NMS system: "
	#strace -t -s 2000 -f -F $EXEC 2>&1 | grep -v stat64 &> /akkada/bin/4.log &
	daemon --user $OSLogin $EXEC

	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $PIDFILE
	return $RETVAL
}	
stop() {
	echo -n $"Shutting down akk@da NMS system: "
	killproc $EXEC
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f $PIDFILE
	return $RETVAL
}
rhstatus() {
	status $EXEC
}
restart() {
	$CFGCHECK
	RETVAL=$?
	[ $RETVAL -ne 0 ] && exit $RETVAL
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	rhstatus
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

cd $CDIR

exit $?

